CREATE DATABASE D2SV DEFAULT CHARACTER SET utf8 ;

USE D2SV;

CREATE TABLE IF NOT EXISTS D2SV.ESTADO (
  ID_ESTADO INT NOT NULL,
  NOME_ESTADO VARCHAR(45) NOT NULL,
  PRIMARY KEY (ID_ESTADO)
);

CREATE TABLE IF NOT EXISTS D2SV.CIDADE (
  ID_CIDADE INT NOT NULL AUTO_INCREMENT,
  NOME_CIDADE VARCHAR(80) NOT NULL,
  PRIMARY KEY (ID_CIDADE)
);

CREATE TABLE IF NOT EXISTS D2SV.CIDADE_ESTADO (
  ID_ESTADO INT NOT NULL,
  ID_CIDADE INT NOT NULL,
  PRIMARY KEY (ID_ESTADO, ID_CIDADE),
  INDEX fk_cidadeEstado_Cidade_idx (ID_CIDADE ASC),
  CONSTRAINT fk_cidadeEstado_Estado    FOREIGN KEY (ID_ESTADO)    REFERENCES D2SV.ESTADO (ID_ESTADO),
  CONSTRAINT fk_cidadeEstado_Cidade    FOREIGN KEY (ID_CIDADE)    REFERENCES D2SV.CIDADE (ID_CIDADE)
);

CREATE TABLE IF NOT EXISTS D2SV.TIPO_USUARIO (
  ID_TIPO_USUARIO INT NOT NULL,
  DESCRICAO_TIPO_USUARIO VARCHAR(45) NOT NULL,
  PRIMARY KEY (ID_TIPO_USUARIO)
);

insert into tipo_usuario value
(1,'Autônomo'),
(2,'Cliente'),
(3,'Administrador');

CREATE TABLE IF NOT EXISTS D2SV.USUARIO (
	ID_USUARIO INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(200) NULL,
	EMAIL VARCHAR(100) NOT NULL,
	SENHA VARCHAR(15) NOT NULL,
	SEXO ENUM('F', 'M') NULL,
	CPF VARCHAR(11) NULL,
	RG VARCHAR(15) NULL,
	DT_NASCIMENTO DATE NULL,
	CELULAR VARCHAR(12) NULL,
	TELEFONE VARCHAR(12) NULL,
	BAIRRO VARCHAR(45) NULL,
	ENDERECO VARCHAR(45) NULL,
	ID_CIDADE INT NOT NULL,
	ID_ESTADO INT NOT NULL,
	CEP VARCHAR(8) NULL,
	COMPLEMENTO VARCHAR(45) NULL,
	ATIVO ENUM('S', 'N') NOT NULL,
	PAGA_PREMIUM ENUM('S', 'N') NOT NULL,
	ID_TIPO_USUARIO INT NOT NULL,
	INDEX fk_tipoUsuario_idx (ID_TIPO_USUARIO ASC),
	UNIQUE INDEX CPF_UNIQUE (CPF ASC),
	INDEX fk_cidadeEstado_idx (ID_ESTADO ASC, ID_CIDADE ASC),
	CONSTRAINT fk_tipoUsuario    FOREIGN KEY (ID_TIPO_USUARIO)		REFERENCES D2SV.TIPO_USUARIO (ID_TIPO_USUARIO),
	CONSTRAINT fk_cidadeEstado   FOREIGN KEY (ID_ESTADO , ID_CIDADE)	REFERENCES D2SV.CIDADE_ESTADO (ID_ESTADO , ID_CIDADE)
);

CREATE TABLE IF NOT EXISTS D2SV.ATUACAO (
	ID_ATUACAO INT NOT NULL,
	AREA VARCHAR(45) NULL,
	PRIMARY KEY (ID_ATUACAO)
);

CREATE TABLE IF NOT EXISTS D2SV.ESPECIALIDADE (
	ID_ESPECIALIDADE INT NOT NULL AUTO_INCREMENT,
	NOME VARCHAR(45) NULL,
	PRIMARY KEY (ID_ESPECIALIDADE)
);

CREATE TABLE IF NOT EXISTS D2SV.PROFISSAO (
	ID INT NOT NULL AUTO_INCREMENT,
	NOME VARCHAR(45) NULL,
	ID_ATUACAO INT NOT NULL,
	PRIMARY KEY (ID),
	INDEX fk_profissaoAtuacao_idx (ID_ATUACAO ASC),
	CONSTRAINT fk_profissaoAtuacao	FOREIGN KEY (ID_ATUACAO)	REFERENCES D2SV.ATUACAO (ID_ATUACAO)
);

CREATE TABLE IF NOT EXISTS D2SV.PROFISSAO_ESPECIALIDADE (
	ID_PROFISSAO INT NOT NULL,
	ID_ESPECIALIDADE INT NOT NULL,
	PRIMARY KEY (ID_PROFISSAO, ID_ESPECIALIDADE),
	INDEX fk_especialidade_idx (ID_ESPECIALIDADE ASC),
	INDEX fk_profissao_idx (ID_PROFISSAO ASC),
	CONSTRAINT fk_profissao	FOREIGN KEY (ID_PROFISSAO)	REFERENCES D2SV.PROFISSAO (ID),
	CONSTRAINT fk_especialidade	FOREIGN KEY (ID_ESPECIALIDADE)	REFERENCES D2SV.ESPECIALIDADE (ID_ESPECIALIDADE)
);

CREATE TABLE IF NOT EXISTS D2SV.PROFISSAO_ESPECIALIDADE_AUTONOMO (
  ID_PROFISSAO INT NOT NULL,
  ID_ESPECIALIDADE INT NOT NULL,
  ID_AUTONOMO INT NOT NULL,
  DESCRICAO_ESPECIALIDADE VARCHAR(200) NULL,
  PRIMARY KEY (ID_PROFISSAO, ID_ESPECIALIDADE, ID_AUTONOMO),
  INDEX fk_ProfEspecAuto_autonomo_idx (ID_AUTONOMO ASC),
  INDEX fk_ProfEspecAuto_prof_espec_idx (ID_PROFISSAO ASC, ID_ESPECIALIDADE ASC),
  CONSTRAINT fk_ProfEspecAuto_prof_espec  FOREIGN KEY (ID_PROFISSAO , ID_ESPECIALIDADE)		REFERENCES D2SV.PROFISSAO_ESPECIALIDADE (ID_PROFISSAO , ID_ESPECIALIDADE),
  CONSTRAINT fk_ProfEspecAuto_autonomo    FOREIGN KEY (ID_AUTONOMO)    						REFERENCES D2SV.USUARIO (ID_USUARIO)
);

#done
CREATE TABLE IF NOT EXISTS D2SV.TIPO_MIDIA (
  ID_TIPO_MIDIA INT NOT NULL AUTO_INCREMENT,
  TIPO_MIDIA VARCHAR(100) NOT NULL,
  PRIMARY KEY (ID_TIPO_MIDIA)
);

CREATE TABLE IF NOT EXISTS D2SV.MULTIMIDIA (
  ID_MULTIMIDIA INT NOT NULL AUTO_INCREMENT,
  CAMINHO_MULTIMIDIA VARCHAR(200) NULL,
  ID_USUARIO INT NOT NULL,
  DESCRICAO_MULTIMIDIA VARCHAR(200) NULL,
  ID_TIPO_MIDIA INT NOT NULL,
  PRIMARY KEY (ID_MULTIMIDIA),
  INDEX fk_multimidia_autonomo_idx (ID_USUARIO ASC),
  INDEX fk_MULTIMIDIA_TIPO_MIDIA1_idx (ID_TIPO_MIDIA ASC),
  CONSTRAINT fk_multimidia_autonomo1    FOREIGN KEY (ID_USUARIO)    REFERENCES D2SV.USUARIO (ID_USUARIO),
  CONSTRAINT fk_MULTIMIDIA_TIPO_MIDIA1    FOREIGN KEY (ID_TIPO_MIDIA)    REFERENCES D2SV.TIPO_MIDIA (ID_TIPO_MIDIA)
);

CREATE TABLE IF NOT EXISTS D2SV.AGENDAMENTO (
  ID INT NOT NULL AUTO_INCREMENT,
  EVENTO VARCHAR(45) NULL,
  NOME_CLIENTE VARCHAR(45) NULL,
  HORARIO_AGENDA DATETIME NULL,
  DESCRICAO VARCHAR(120) NULL,
  VALOR_SERVICO FLOAT NULL,
  VALOR_RECEBIDO FLOAT NULL,
  ID_PROFISSAO INT NOT NULL,
  ID_ESPECIALIDADE INT NOT NULL,
  ID_AUTONOMO INT NOT NULL,
  ID_CLIENTE INT NULL,
  PRIMARY KEY (ID),
  INDEX fk_AGENDAMENTO_PROFISSAO_ESPECIALIDADE_AUTONOMO1_idx (ID_PROFISSAO ASC, ID_ESPECIALIDADE ASC, ID_AUTONOMO ASC),
  INDEX fk_AGENDAMENTO_USUARIO1_idx (ID_CLIENTE ASC),
  CONSTRAINT fk_AGENDAMENTO_PROFISSAO_ESPECIALIDADE_AUTONOMO1    FOREIGN KEY (ID_PROFISSAO , ID_ESPECIALIDADE , ID_AUTONOMO)    REFERENCES D2SV.PROFISSAO_ESPECIALIDADE_AUTONOMO (ID_PROFISSAO , ID_ESPECIALIDADE , ID_AUTONOMO),
  CONSTRAINT fk_AGENDAMENTO_USUARIO1    FOREIGN KEY (ID_CLIENTE)    REFERENCES D2SV.USUARIO (ID_USUARIO)
);

CREATE TABLE IF NOT EXISTS D2SV.MOTIVO (
	ID INT NOT NULL AUTO_INCREMENT,
	MOTIVO VARCHAR(200) NOT NULL,
	ID_USUARIO INT NOT NULL,
	ID_ADMIN_DESATIV INT NOT NULL,
	DT_INATIVACAO DATE NOT NULL,
	ID_ADMIN_ATIV INT NULL,
	DT_ATIVACAO DATE NULL,
  MOTIVO_ATIVACAO VARCHAR(200) NULL,
  PRIMARY KEY (ID),
  INDEX fk_motivo_usuario_idx (ID_USUARIO ASC),
  INDEX fk_motivo_admin_desativ_idx (ID_ADMIN_DESATIV ASC),
  INDEX fk_motivo_admin_ativ_idx (ID_ADMIN_ATIV ASC),
  CONSTRAINT fk_motivo_usuario
    FOREIGN KEY (ID_USUARIO)
    REFERENCES D2SV.USUARIO (ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_motivo_admin_desativ
    FOREIGN KEY (ID_ADMIN_DESATIV)
    REFERENCES D2SV.USUARIO (ID_USUARIO)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_motivo_admin_ativ
    FOREIGN KEY (ID_ADMIN_ATIV)
    REFERENCES D2SV.USUARIO (ID_USUARIO)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE TABLE IF NOT EXISTS D2SV.OCORRENCIA (
  ID_OCORRENCIA INT NOT NULL AUTO_INCREMENT,
  DESCRICAO VARCHAR(45) NULL,
  ID_CLIENTE INT NOT NULL,
  ID_AUTONOMO INT NOT NULL,
  PRIMARY KEY (ID_OCORRENCIA),
  INDEX fk_ocorrencia_usuario_idx (ID_CLIENTE ASC),
  INDEX fk_ocorrencia_autonomo_idx (ID_AUTONOMO ASC),
  CONSTRAINT fk_ocorrencia_usuario
    FOREIGN KEY (ID_CLIENTE)
    REFERENCES D2SV.USUARIO (ID_USUARIO)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_ocorrencia_autonomo
    FOREIGN KEY (ID_AUTONOMO)
    REFERENCES D2SV.USUARIO (ID_USUARIO)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE TABLE IF NOT EXISTS D2SV.FAVORITO (
  ID_FAVORITO INT NOT NULL AUTO_INCREMENT,
  DESCRICAO VARCHAR(200) NULL,
  ID_USUARIO INT NOT NULL,
  ID_AUTONOMO INT NOT NULL,
  PRIMARY KEY (ID_FAVORITO),
  INDEX fk_favoritos_usuario_idx (ID_USUARIO ASC),
  INDEX fk_favoritos_autonomo_idx (ID_AUTONOMO ASC),
  CONSTRAINT fk_favoritos_usuario
    FOREIGN KEY (ID_USUARIO)
    REFERENCES D2SV.USUARIO (ID_USUARIO)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_favoritos_autonomo
    FOREIGN KEY (ID_AUTONOMO)
    REFERENCES D2SV.USUARIO (ID_USUARIO)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE TABLE IF NOT EXISTS D2SV.AVALIACAO_SERVICO (
  ID_AVALIACAO INT NOT NULL AUTO_INCREMENT,
  DESCRICAO VARCHAR(45) NOT NULL,
  PONTUACAO INT NULL,
  ID_USUARIO INT NOT NULL,
  ID_AUTONOMO INT NOT NULL,
  PRIMARY KEY (ID_AVALIACAO),
  INDEX fk_avaliacao_servico_usuario_idx (ID_USUARIO ASC), 
  INDEX fk_avaliacao_servico_autonomo_idx (ID_AUTONOMO ASC),
  CONSTRAINT fk_avaliacao_servico_usuario    FOREIGN KEY (ID_USUARIO)    REFERENCES D2SV.USUARIO (ID_USUARIO),
  CONSTRAINT fk_avaliacao_servico_autonomo    FOREIGN KEY (ID_AUTONOMO)    REFERENCES D2SV.USUARIO (ID_USUARIO)
);