CREATE DATABASE SICABD;
USE SICABD;

CREATE TABLE IF NOT EXISTS SICABD.TIPO_USUARIO (
	ID_TIPO_USUARIO INT NOT NULL,
	DESCRICAO_TIPO_USUARIO VARCHAR(45) NOT NULL,
	PRIMARY KEY (ID_TIPO_USUARIO));

insert into tipo_usuario value
(1,'Autônomo'),
(2,'Cliente'),
(3,'Administrador');

CREATE TABLE IF NOT EXISTS SICABD.USUARIO (
	ID INT NOT NULL AUTO_INCREMENT,
	NOME VARCHAR(45) NULL,
	EMAIL VARCHAR(45) NOT NULL,
	SENHA VARCHAR(45) NOT NULL,
	CPF VARCHAR(45) NULL,
	RG VARCHAR(45) NULL,
	TELEFONE VARCHAR(45) NULL,
	CELULAR VARCHAR(45) NULL,
	SEXO VARCHAR(45) NULL,
	DT_NASCIMENTO VARCHAR(45) NULL,
	CEP VARCHAR(45) NULL,
	ESTADO VARCHAR(45) NULL,
	CIDADE VARCHAR(45) NULL,
	ENDERECO VARCHAR(45) NULL,
	BAIRRO VARCHAR(45) NULL,
	COMPLEMENTO VARCHAR(45) NULL,
	PAGA_PREMIUM TINYINT(1) NOT NULL DEFAULT 0,
	ID_TIPO_USUARIO INT NOT NULL,
	ATIVO TINYINT(1) NOT NULL DEFAULT 1,
	PRIMARY KEY (ID),
	INDEX fk_tipo_usuario_idx (ID_TIPO_USUARIO ASC),
	UNIQUE INDEX CPF_UNIQUE (CPF ASC),
	CONSTRAINT fk_tipo_usuario
	FOREIGN KEY (ID_TIPO_USUARIO)
	REFERENCES SICABD.TIPO_USUARIO (ID_TIPO_USUARIO)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION);

CREATE TABLE IF NOT EXISTS SICABD.ATUACAO (
	ID_ATUACAO INT NOT NULL,
	AREA VARCHAR(45) NULL,
	PRIMARY KEY (ID_ATUACAO));

CREATE TABLE IF NOT EXISTS SICABD.ESPECIALIDADE (
	ID_ESPECIALIDADE INT NOT NULL AUTO_INCREMENT,
	NOME VARCHAR(45) NULL,
	PRIMARY KEY (ID_ESPECIALIDADE));

CREATE TABLE IF NOT EXISTS SICABD.PROFISSAO (
	ID INT NOT NULL AUTO_INCREMENT,
	NOME VARCHAR(45) NULL,
	ID_ATUACAO INT NOT NULL,
	PRIMARY KEY (ID),
	INDEX fk_profissao_atuacao_idx (ID_ATUACAO ASC),
	CONSTRAINT fk_profissao_atuacao
	FOREIGN KEY (ID_ATUACAO)
	REFERENCES SICABD.ATUACAO (ID_ATUACAO)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION);

CREATE TABLE IF NOT EXISTS SICABD.PROFISSAO_ESPECIALIDADE (
	ID_PROFISSAO INT NOT NULL,
	ID_ESPECIALIDADE INT NOT NULL,
	PRIMARY KEY (ID_PROFISSAO, ID_ESPECIALIDADE),
	INDEX fk_especialidade_idx (ID_ESPECIALIDADE ASC),
	INDEX fk_profissao_idx (ID_PROFISSAO ASC),
	CONSTRAINT fk_profissao
	FOREIGN KEY (ID_PROFISSAO)
	REFERENCES SICABD.PROFISSAO (ID)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION,
	CONSTRAINT fk_especialidade
	FOREIGN KEY (ID_ESPECIALIDADE)
	REFERENCES SICABD.ESPECIALIDADE (ID_ESPECIALIDADE)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION);

CREATE TABLE IF NOT EXISTS SICABD.PROFISSAO_ESPECIALIDADE_AUTONOMO (
  ID_PROFISSAO INT NOT NULL,
  ID_ESPECIALIDADE INT NOT NULL,
  ID_AUTONOMO INT NOT NULL,
  DESCRICAO_ESPECIALIDADE VARCHAR(200) NULL,
  PRIMARY KEY (ID_PROFISSAO, ID_ESPECIALIDADE, ID_AUTONOMO),
  INDEX fk_autonomo_especialidade_profissao_idx (ID_AUTONOMO ASC),
  INDEX fk_profissao_especialidade_idx (ID_PROFISSAO ASC, ID_ESPECIALIDADE ASC),
  CONSTRAINT fk_profissao_especialidade
    FOREIGN KEY (ID_PROFISSAO , ID_ESPECIALIDADE)
    REFERENCES SICABD.PROFISSAO_ESPECIALIDADE (ID_PROFISSAO , ID_ESPECIALIDADE)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_autonomo_especialidade_profissao
    FOREIGN KEY (ID_AUTONOMO)
    REFERENCES SICABD.USUARIO (ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE TABLE IF NOT EXISTS SICABD.TIPO_MIDIA (
	ID_TIPO_MIDIA INT NOT NULL AUTO_INCREMENT,
	TIPO_MIDIA VARCHAR(100) NOT NULL,
	PRIMARY KEY (ID_TIPO_MIDIA));

CREATE TABLE IF NOT EXISTS SICABD.MULTIMIDIA (
	ID_MULTIMIDIA INT NOT NULL AUTO_INCREMENT,
	CAMINHO_MULTIMIDIA VARCHAR(200) NULL,
	ID_USUARIO INT NOT NULL,
	DESCRICAO_MULTIMIDIA VARCHAR(200) NULL,
	ID_TIPO_MIDIA INT NOT NULL,
	PRIMARY KEY (ID_MULTIMIDIA),
	INDEX fk_multimidia_autonomo_idx (ID_USUARIO ASC),
	INDEX fk_multimidia_tipo_midia_idx (ID_TIPO_MIDIA ASC),
	CONSTRAINT fk_multimidia_autonomo
	FOREIGN KEY (ID_USUARIO)
	REFERENCES SICABD.USUARIO (ID)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION,
	CONSTRAINT fk_multimidia_tipo_midia
	FOREIGN KEY (ID_TIPO_MIDIA)
	REFERENCES SICABD.TIPO_MIDIA (ID_TIPO_MIDIA)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION);

CREATE TABLE IF NOT EXISTS SICABD.AGENDAMENTO (
  ID INT NOT NULL AUTO_INCREMENT,
  EVENTO VARCHAR(45) NULL,
  NOME_CLIENTE VARCHAR(45) NULL,
  HORARIO_AGENDA DATETIME NULL,
  DESCRICAO VARCHAR(45) NULL,
  VALOR_SERVICO FLOAT NULL,
  VALOR_RECEBIDO FLOAT NULL,
  ID_PROFISSAO INT NOT NULL,
  ID_ESPECIALIDADE INT NOT NULL,
  ID_AUTONOMO INT NOT NULL,
  ID_CLIENTE INT NULL,
  PRIMARY KEY (ID),
  INDEX fk_agenda_profissao_especialidade_auto_idx (ID_PROFISSAO ASC, ID_ESPECIALIDADE ASC, ID_AUTONOMO ASC),
  INDEX fk_agenda_cliente_idx (ID_CLIENTE ASC),
  CONSTRAINT fk_agenda_profissao_especialidade_auto
    FOREIGN KEY (ID_PROFISSAO , ID_ESPECIALIDADE , ID_AUTONOMO)
    REFERENCES SICABD.PROFISSAO_ESPECIALIDADE_AUTONOMO (ID_PROFISSAO , ID_ESPECIALIDADE , ID_AUTONOMO)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_agenda_cliente
    FOREIGN KEY (ID_CLIENTE)
    REFERENCES SICABD.USUARIO (ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE TABLE IF NOT EXISTS SICABD.MOTIVO (
  ID INT NOT NULL AUTO_INCREMENT,
  MOTIVO VARCHAR(200) NOT NULL,
  ID_USUARIO INT NOT NULL,
  ID_ADMIN_DESATIV INT NOT NULL,
  DT_INATIVACAO DATE NOT NULL,
  ID_ADMIN_ATIV INT NULL,
  DT_ATIVACAO DATE NULL,
  MOTIVO_ATIVACAO VARCHAR(200) NULL,
  PRIMARY KEY (ID),
  INDEX fk_motivo_usuario_idx (ID_USUARIO ASC),
  INDEX fk_motivo_admin_desativ_idx (ID_ADMIN_DESATIV ASC),
  INDEX fk_motivo_admin_ativ_idx (ID_ADMIN_ATIV ASC),
  CONSTRAINT fk_motivo_usuario
    FOREIGN KEY (ID_USUARIO)
    REFERENCES SICABD.USUARIO (ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_motivo_admin_desativ
    FOREIGN KEY (ID_ADMIN_DESATIV)
    REFERENCES SICABD.USUARIO (ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_motivo_admin_ativ
    FOREIGN KEY (ID_ADMIN_ATIV)
    REFERENCES SICABD.USUARIO (ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE TABLE IF NOT EXISTS SICABD.OCORRENCIA (
  ID_OCORRENCIA INT NOT NULL AUTO_INCREMENT,
  DESCRICAO VARCHAR(45) NULL,
  ID_CLIENTE INT NOT NULL,
  ID_AUTONOMO INT NOT NULL,
  PRIMARY KEY (ID_OCORRENCIA),
  INDEX fk_ocorrencia_usuario_idx (ID_CLIENTE ASC),
  INDEX fk_ocorrencia_autonomo_idx (ID_AUTONOMO ASC),
  CONSTRAINT fk_ocorrencia_usuario
    FOREIGN KEY (ID_CLIENTE)
    REFERENCES SICABD.USUARIO (ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_ocorrencia_autonomo
    FOREIGN KEY (ID_AUTONOMO)
    REFERENCES SICABD.USUARIO (ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE TABLE IF NOT EXISTS SICABD.FAVORITO (
  ID_FAVORITO INT NOT NULL AUTO_INCREMENT,
  DESCRICAO VARCHAR(200) NULL,
  ID_USUARIO INT NOT NULL,
  ID_AUTONOMO INT NOT NULL,
  PRIMARY KEY (ID_FAVORITO),
  INDEX fk_favoritos_usuario_idx (ID_USUARIO ASC),
  INDEX fk_favoritos_autonomo_idx (ID_AUTONOMO ASC),
  CONSTRAINT fk_favoritos_usuario
    FOREIGN KEY (ID_USUARIO)
    REFERENCES SICABD.USUARIO (ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_favoritos_autonomo
    FOREIGN KEY (ID_AUTONOMO)
    REFERENCES SICABD.USUARIO (ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE TABLE IF NOT EXISTS SICABD.AVALIACAO_SERVICO (
  ID_AVALIACAO INT NOT NULL AUTO_INCREMENT,
  DESCRICAO VARCHAR(45) NOT NULL,
  PONTUACAO INT NULL,
  ID_USUARIO INT NOT NULL,
  ID_AUTONOMO INT NOT NULL,
  PRIMARY KEY (ID_AVALIACAO),
  INDEX fk_avaliacao_servico_usuario_idx (ID_USUARIO ASC), 
  INDEX fk_avaliacao_servico_autonomo_idx (ID_AUTONOMO ASC),
  CONSTRAINT fk_avaliacao_servico_usuario
    FOREIGN KEY (ID_USUARIO)
    REFERENCES SICABD.USUARIO (ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_avaliacao_servico_autonomo
    FOREIGN KEY (ID_AUTONOMO)
    REFERENCES SICABD.USUARIO (ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

select * from usuario;